---
version: "3"

tasks:
  oas-download:
    desc: Download OpenAPI specification
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/inference-gateway/refs/heads/main/openapi.yaml

  generate:
    desc: Generate Go types from OpenAPI specification
    cmds:
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest --package=sdk --generate types -o generated_types.go openapi.yaml

  lint:
    desc: Runs golangci-lint
    cmds:
      - golangci-lint run

  tidy:
    desc: Runs go mod tidy
    cmds:
      - go mod tidy

  test:
    desc: Runs go test
    cmds:
      - go test -v ./...

  docs:
    desc: Run http server on port :6060 with documentation
    cmds:
      - godoc -http=:6060
