---
version: "3"

tasks:
  oas-download:
    desc: Download OpenAPI specification
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/inference-gateway/refs/heads/main/openapi.yaml
